name: mad_cw5
description: A Flutter app for a virtual aquarium with animated fish images.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.3
  flutter_colorpicker: ^1.0.3  # Added for color picker

flutter:
  uses-material-design: true

  # Add assets for fish images
  assets:
    - assets/fish1.png
    - assets/fish2.png
    - assets/fish3.png
